apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: student-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: gcr.io/banded-elevator-272716/student-service:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: student-service-service
  labels:
    name: student-service-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: student-service
  type: LoadBalancer